[theme]
# Leave defaults; keep this file for future theming.

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[ui]
hideTopBar = false

[global]
disableWatchdogWarning = true
