[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "path-finding-game-app"
version = "0.1.0"
description = "Streamlit app to explore Path Finding games."
readme = "path_finding_game_app.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = jparisu}]

[tool.hatch.build.targets.wheel]
packages = ["src/ml_classification_study"]
